#!/bin/tcsh
source ./code/code.main/custom-tcshrc      # customize shell environment

##
## USAGE: pipeline-errors INPUT-DIR
##

if ($#argv != 1) then
  grep '^##' $0
  exit
endif

set inpdir = $1
set outdir = errors

if (-e $outdir) rm -rf $outdir

mkdir -p $outdir

# first check job stderr output files
find $inpdir/ -name 'job.*' -print0 | xargs -0 grep -iwE 'usage|error|segmentation|not found|join.*sort|no such file|syntax|terminate|permission denied' | grep -vE 'Tcl command execution failed|Module .* conflicts with the currently loaded module|Module .* depends on one of the module|will result in an error in the future' >&! $outdir/error.log


