#!/bin/tcsh

##
## USAGE: pipeline-clean-stats
##

if ($#argv != 0) then
  grep '^##' $0
  exit
endif

set D = `grep pipeline-master-explorer.r __*/run | sed 's/ *[^ ]\+ *$//' | sed 's/:.* /:/' | grep '"\*"' | cut -d'/' -f1`
echo $D | tr ' ' '\n'

echo -n "Delete all results in the directories listed above? "
set x = $<
if ("$x" != "YES") then
  echo "Aborting..."
  exit
endif

foreach d ($D)
  echo "Deleting results in directory $d..."
  rm -rf $d/results
end

