#!/bin/tcsh

##
## USAGE: pipeline-reverse-sync
##

if ($#argv != 0) then
  grep '^##' $0
  exit
endif

# init
set analysis_dir = `readlink -f $0 | sed 's/[^/]\+$//'`/../..
set repo_code_dir = code.origin
cd $analysis_dir
set analysis_dir = `pwd`
set pipeline_name = `readlink -f code | sed 's/.*\.//'`

echo "Repository code directory = $repo_code_dir"
echo "Analysis directory = $analysis_dir"
echo "Pipeline = $pipeline_name"

# sync (dry-run first)
rsync -nauv --exclude=src code.repo/ $repo_code_dir/
echo -n "REVERSE Sync? Type 'YES' to proceed: "
set x = $<
if ($x == YES) then
  rsync -auv --exclude=src code.repo/ $repo_code_dir/
endif





