#!/bin/tcsh
source ./code/code.main/custom-tcshrc      # customize shell environment

##
## USAGE: pipeline-errors INPUT-DIR
##

if ($#argv != 1) then
  grep '^##' $0
  exit
endif

set inpdir = $1
set outdir = errors

if (-e $outdir) rm -rf $outdir

mkdir -p $outdir

# first check job stderr output files
find $inpdir/ -name 'job.*' -print0 | xargs -0 grep -iE 'usage|error|segmentation|not found|join.*sort|no such file|syntax|terminate' | grep -vE 'Tcl command execution failed|Module .* conflicts with the currently loaded module|Module .* depends on one of the module|will result in an error in the future' >&! $outdir/error.log

exit


# then, check exit status of each job
set jfiles = `find $inpdir -name 'job.*id'`
foreach f ($jfiles)
  scripts-send2err "Processing $f..."
  set jid = `cut -d' ' -f3 $f`
  set outf = $outdir/job.$jid.txt
  echo "FILE: $f" >! $outf
  echo "JOB-ID: $jid" >> $outf
  qacct -j $jid >>& $outf
end

grep -E '^failed|^exit_status' $outdir/job.*.txt | sed 's/ *$//' | grep -v ' 0$' >> $outdir/error.log


