#!/bin/tcsh

#SBATCH -J wait-giveok
#SBATCH --time=0-00:05:00
#SBATCH -p cpu_dev
#SBATCH -n 1
#SBATCH --mem=1G
#SBATCH -o ${1}.out
#SBATCH -e ${1}.err

source ./code/code.main/custom-tcshrc      # customize shell environment

#file_to_write=$1

echo "Done waiting." >! $1

