#!/bin/tcsh
source ./code/code.main/custom-tcshrc      # customize shell environment

##
## USAGE: scripts-wait-qsub JOB-IDS [SECONDS=5]
##

set job_ids = ($1)
if ($#job_ids == 0) exit

set sec = $2
if ($sec == '') set sec = 10

set flag = `scripts-create-temp`
echo "touch $flag.done" >> $flag
chmod +x $flag

#scontrol show jobid=$job_id | grep "JobState" | cut -d= -f2 | cut -d' ' -f1 >& /dev/null
#(qsub -hold_jid `echo $job_ids | tr ' ' ','` -cwd ./$flag) >& /dev/null

#echo "sbatch --depend=afterok:`echo $job_ids | tr ' ' ':'` ./code/code.main/scripts-qsub-wait-giveok $flag.done"
sbatch --priority=TOP --depend=afterany:`echo $job_ids | tr ' ' ':'` ./code/code.main/scripts-qsub-wait-giveok $flag.done >! $flag.id 

while (1)
  sleep $sec
#  ls *.done
  if (-e $flag.done) break
end
rm -f ${flag}*

