#!/bin/tcsh

##
## USAGE: generate-param-scripts
##

if ($#argv != 0) then
  grep '^##' $0
  exit
endif

foreach method (inter intra-max)
  foreach f (params.hicratio.*.tcsh)
    set fnew = `echo $f | sed "s/hicratio/hic$method/"`
    echo "$f -----> $fnew"
    cat $f | sed "s/^--method=ratio/--method=$method/" >! $fnew
  end
end

chmod +x params.*.tcsh

