#!/bin/tcsh
source ./code/code.main/custom-tcshrc      # customize shell environment

##
## USAGE: run [--dry-run]
##

#% This step takes HiCPlotter snapshots in pairs of samples. 
#% TABLES: 
#% FIGURES:

# process command-line inputs
if ($#argv > 1) then
  grep '^##' $0 | scripts-send2err
  exit
endif

set opt = "$1"

# setup
set op = hicplotter-diff
set inpdirs = "inpdirs/*"
set results = results
scripts-create-path $results/
scripts-send2err "=== Operation = $op ============="
set resources = 1,20G
set cmd = "./code/code.main/scripts-qsub-wrapper $resources ./code/hicseq-$op.tcsh"

# generate run script
Rscript ./code/code.main/pipeline-master-explorer.r -v --filter-branch='matrix-prep.*/matrix-filtered.by_sample.res_40kb' --exclude-branch='matrix-estimated|by_group' "$cmd" $results/$op "params/params.*.tcsh" "$inpdirs" "" "sample" 2

# run and wait until done!
set max_jobs = 50
if ("$opt" != "--dry-run") scripts-submit-jobs ./$results/.db/run $max_jobs



