#!/bin/tcsh

##
## USAGE: generate-param-files NUMBER-OF-BOUNDARIES-PER-CATEGORY
##

if ($#argv != 1) then
  grep '^##' $0
  exit
endif

set n = $1

foreach k (001 002 003 004 005 006)
  set out = params.k_$k.n_$n.tcsh
  cat template.tcsh | sed "s/<optimal>/k=$k/" | sed "s/<n>/$n/" >! $out
  chmod +x $out
end

