#!/bin/tcsh
source ./code/code.main/custom-tcshrc      # customize shell environment

##
## USAGE: run [--dry-run]
##

# ~~~ Entries for auto-report ~~~ #
#TITLE: Peak Annotation
#DESCRIPTION: Peak Annotation By Sample uing ChIPseeker
#FIGURE: peaks-coverage.pdf anno-piechart.pdf upsetplot.pdf
#PARAMS: params.standard.tcsh
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

# process command-line inputs
if ($#argv > 1) then
  grep '^##' $0 | scripts-send2err
  exit 1
endif

set opt = "$1"

# setup
set op = peakanno
set inpdirs = "inpdirs/peaks"
set results = results
scripts-create-path $results/
scripts-send2err "=== Operation = $op ============="
set resources = 1
set cmd = "./code/code.main/scripts-qsub-wrapper $resources ./code/chipseq-$op.tcsh"

# check for missing packages
source ./params/params.standard.tcsh
scripts-send2err " R: `which R` "
scripts-send2err " Rscript: `which Rscript` "
Rscript ./code/code.main/install-r-packages.r

# generate run script
Rscript ./code/code.main/pipeline-master-explorer.r -v "$cmd" $results/$op "params/params.*.tcsh" "$inpdirs" "" "." 1

# run and wait until done!
if ("$opt" != "--dry-run") scripts-submit-jobs ./$results/.db/run



