#!/bin/tcsh

##
## USAGE: run-find
##

if ($#argv != 0) then
  grep '^##' $0
  exit
endif

#foreach D (results/compare-matrices.by_sample.standard/matrix-estimated.by_sample.prep_*)
foreach D (results/compare-matrices.by_sample.standard)
  echo "==> $D"
  set Jid = $D/matrix-*.by_sample.standard/matrix-filtered.by_sample.res_*kb/filter-resample.by_sample.reads_70M/filter.by_sample.standard/align.by_sample.bowtie2/*/*/job.id
  set Jdone = $D/matrix-*.by_sample.standard/matrix-filtered.by_sample.res_*kb/filter-resample.by_sample.reads_70M/filter.by_sample.standard/align.by_sample.bowtie2/*/*/job.vars.tsv
  set X = $D/matrix-*.by_sample.standard/matrix-filtered.by_sample.res_*kb/filter-resample.by_sample.reads_70M/filter.by_sample.standard/align.by_sample.bowtie2/*/*/cor.pearson.prep_none.tsv
  echo $#Jid $#Jdone $#X
  wc -l $X | grep -vi total | awk '{print $1}' | sort | uniq -c
  head -1 $X | grep ^SAMPLE | sort | uniq -c
end



